### ISSUE TITLE
Metrics default dashboard view shows constant loading spinner

### ISSUE THREAD

**Issue by ashley-marie** [microsoft/data-accelerator#139]
**Describe the bug**
When viewing the metrics dashboard (without clicking into a specific Flow) there is a spinning loading indicator that does not finish or provide more information. 

**To Reproduce**
1. Run Data Accelerator local deployment
2. Go to http://localhost:49080/home
3. Open the Metrics tab. Do not click on any listed Flows.
4. Observe spinner

**Expected behavior**
Loading completes, or display a message indicating that I should click on a Flow to view its metrics. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12385296/64292079-6612fe00-cf1e-11e9-9fc7-67554574dac0.png)

**Version of Data Accelerator**
How do I find this information? 
- Services:
 - DataProcessing
 - WebSite:

**Desktop (please complete the following information):**
 - macOS Mojave 10.14.4
 - Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by rohit489** [comment]
Fixed #132
