### ISSUE TITLE
Enable support for Snapshot packages in Git Maven Repo

### ISSUE THREAD

**Issue by carlbrochu** [microsoft/data-accelerator#14]
**Describe the bug**
No way to host snapshot jar from master on Maven repo

**To Reproduce**
1. Go to DataProcessing
2. Open datax-host pom file
3. Notice it depends on the non-snapshot version

**Expected behavior**
Maven hosted Snapshot packages

**Comment by rohit489** [comment]
Fixed with Pull Request #56
