### ISSUE TITLE
Can't install using docker

### ISSUE THREAD

**Issue by leogomes** [microsoft/data-accelerator#171]
**Describe the bug**
Cannot pull image from DockerHub

docker pull mcr.microsoft.com/datax/dataxlocal
Using default tag: latest
Error response from daemon: manifest for mcr.microsoft.com/datax/dataxlocal:latest not found: manifest unknown: manifest tagged by "latest" is not found
❯ docker pull mcr.microsoft.com/datax/dataxlocal:v1.2
Error response from daemon: manifest for mcr.microsoft.com/datax/dataxlocal:v1.2 not found: manifest unknown: manifest tagged by "v1.2" is not found
❯ docker pull mcr.microsoft.com/datax/dataxlocal:v1.1
Error response from daemon: manifest for mcr.microsoft.com/datax/dataxlocal:v1.1 not found: manifest unknown: manifest tagged by "v1.1" is not found
❯ docker pull mcr.microsoft.com/datax/dataxlocal:v1
Error response from daemon: manifest for mcr.microsoft.com/datax/dataxlocal:v1 not found: manifest unknown: manifest tagged by "v1" is not found

**To Reproduce**
Run ``docker pull mcr.microsoft.com/datax/dataxlocal``

**Expected behavior**
Image can be pulled

**Desktop (please complete the following information):**
 - OS: Mac
- docker -v
Docker version 19.03.12, build 48a66213fe

**Comment by carlbrochu** [comment]
Thanks for reaching out and for your interest in Data Accelerator as well as logging the Github issue regarding the Docker image.  We have taken down the Docker image recently to make a updates to it.  This will take a couple more days as we validate the changes and the rest of the functionality.  We will keep you posted when the image is available again.

Let us know if you have more questions, I would be happy to learn more about your scenarios and how Data Accelerator can help
Thanks!
Carl

**Comment by rohit489** [comment]
Docker image is now available. For instructions on how to setup please see - [Local-mode-with-Docker](https://github.com/microsoft/data-accelerator/wiki/Local-mode-with-Docker)
