### ISSUE TITLE
Support for Databricks

### ISSUE THREAD

**Issue by carlbrochu** [microsoft/data-accelerator#63]
**Is your feature request related to a problem? Please describe.**
Hosting Data Accelerator should also work with Databricks as the compute resource.

**Describe the solution you'd like**
Databricks integration

**Additional context**
The Data Accelerator is looking into adding support for Data Bricks

**Comment by tylorhl** [comment]
Out of curiosity, is the goal here to simply take advantage of the compute resources provided by Databricks? Or is the intent to also utilize Databricks features like Notebooks and the like?

Either way, the API endpoint of interest for this would likely be here:
https://docs.azuredatabricks.net/api/latest/jobs.html#runs-submit

**Comment by carlbrochu** [comment]
Right, taking advantage of the compute or an existing cluster is the goal here.  Users can use the notebooks  on the cluster, or any feature, if Data Accelerator instantiate the cluster.

**Comment by carlbrochu** [comment]
This is part of the 1.2 release
